"use client";
import { Heebo } from "next/font/google";
import Head from "next/head";
import styled from "@emotion/styled";

const heebo = Heebo({ subsets: ["latin"] });

import { trpc } from '~/utils/api';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// here we wrap all of our pages with TrpcProvider to enable the client to invoke RPCs

type Props = {
  children: React.ReactNode
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
        <Head>
          <title>LT Showcase</title>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
        <Main className={heebo.className}>{children}</Main>
            {children}
        </body>
    </html>
  )
}

const Main = styled.main({
  display: "flex",
  width: "100%",
  height: "100%",
});


export default trpc.withTRPC(RootLayout);
